version: '3.9'

services:

  lessons-serv-app:
    build:
      dockerfile: ./Dockerfile
    container_name: lessonsserv
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - lessons-db
  lessons-db:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lessons_service
      - POSTGRES_USER=dakz
      - POSTGRES_PASSWORD=123321

